api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "appai-base-variant-guard"
type = "function"
uid = "253c89d9-bb5b-7ebf-da40-ed99308bb6b09d7cdad9"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
